# Parent Image
FROM python:3.12-slim

# Set Working Directory
WORKDIR /usr/src/app

# Copy source code to working directory
COPY . .

# Install requirements located in requirements.txt
RUN pip install -r requirements.txt
